### PR TITLE
Fix tab click in launchpad storybook

### LINKED ISSUE #29: [LaunchPad] Clicking on tab title in storybook does fun stuff
I heard you liked stories, so I put stories in stories in stories :)

screenshot at dec 25 22-38-55

Eventually, it breaks the story navigation too (clicking on another story doesn't do anything)

### PR DESCRIPTION
**Pull request by nchevobbe**
Pass the actual onClick handler as a props from LaunchpadApp to LandingPage so the current behavior
still works.
In storybook, when creating the LandingPage, pass an action logger so we don't have story inception anymore

Fixes #29

### CODE REVIEW

**Comment by nchevobbe** [comment]
@juliandescottes sending this your way, since Jason is on PTO this week (I think ?)

File: packages/devtools-launchpad/stories/index.js [hunk 1]
```diff
@@ -36,7 +36,8 @@ const getTabs = (tabs, state) => {
 
 const renderLandingPage = (props) => {
   return React.DOM.div({}, React.createElement(LandingPage, Object.assign({
-    onFilterChange: action("FILTER_TABS")
+    onFilterChange: action("FILTER_TABS"),
```
Comment (juliandescottes) [inline packages/devtools-launchpad/stories/index.js]: was a bit puzzled by the inconsistency between FILTER_TABS and onTabClick. I suppose FILTER_TABS refers to the action, while onTabClick is never connected to any actual action.

From the LandingPage point of view, onFilterChange by itself is not linked to the FILTER_TABS action either. Maybe FILTER_TABS -> onFilterChange ?

File: packages/devtools-launchpad/src/components/LandingPage.js [hunk 2]
```diff
@@ -65,9 +66,7 @@ const LandingPage = React.createClass({
         tabs.valueSeq().map(tab => dom.li(
           { "className": "tab",
```
Comment (jasonLaster) [inline packages/devtools-launchpad/src/components/LandingPage.js]: hmm, the keys probably don't need to be quotes

File: packages/devtools-launchpad/stories/index.js [hunk 3]
```diff
@@ -36,7 +36,8 @@ const getTabs = (tabs, state) => {
...
+    onTabClick: action("onTabClick")
```
Comment (jasonLaster) [inline packages/devtools-launchpad/stories/index.js]: nice
