### PR TITLE
 Better function name in Error stacktrace. 

### LINKED ISSUE #959: Use `getFunctionName` from Function rep in the Error rep stacktrace
`getFunctionName` is an helper that get rid of cryptic `/<` symbols in the function name.
We should call it in the Error rep stacktrace to have nicer function names.

Since it takes a grip, and not a string, it should be split into 2 functions so we can handle strings.

### PR DESCRIPTION
**Pull request by nchevobbe**
Fixes #959.

Built on top of https://github.com/devtools-html/devtools-core/pull/973, only https://github.com/devtools-html/devtools-core/commit/4c4accc965f9a9f233ce2837b956aaed10600d0f is relevant here.

- Display `<anonymous>` for unnamed functions.
- Call cleanFunctionName on it.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Nice

File: packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap [hunk 1]
```diff
@@ -15,7 +15,9 @@ exports[`Error - Eval error renders with expected text for an EvalError 1`] = `
     <span
       className="objectBox-stackTrace-fn"
       key="fn0"
-    />
+    >
```
Comment (gregtatum) [inline packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap]: I believe you landed the better snapshots, thanks for easier reading here.

File: packages/devtools-reps/src/reps/tests/error.js [hunk 2]
```diff
@@ -311,3 +311,24 @@ describe("Error - DOMException", () => {
...
+
+describe("Error - base-loader.js", () => {
+  const stub = stubs.get("base-loader Error");
+
+  it("renders as expected without mode", () => {
+    const renderedComponent = shallow(ErrorRep.rep({
+      object: stub
+    }));
+
+    expect(renderedComponent).toMatchSnapshot();
```
Comment (gregtatum) [inline packages/devtools-reps/src/reps/tests/error.js]: Snapshots work for me!
